### ISSUE TITLE
Add stories / blogs already written

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/sensors.AFRICA#1]
## Description

We should add stories / blogs already written about sensors.AFRICA to the landing page.

## Tasks

- [ ] Sketch out design
- [ ] Implement design

**Comment by yazminjumaali** [comment]
Are you working on this @DavidLemayian?

Blog post:

https://medium.com/code-for-africa/measuring-nairobis-air-quality-using-locally-assembled-low-cost-sensors-94a356885120
