### ISSUE TITLE
Create coming soon alert/pop-up for water + sound buttons 

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfricaLabs/sensors.AFRICA#100]
## Description

We're still to roll out water and sound pages so should have coming soon alerts / pop-ups when buttons on homepage and navbar are clicked.

## Screenshots

**Navbar buttons**
<img width="1668" alt="screen shot 2018-10-11 at 16 40 48" src="https://user-images.githubusercontent.com/877919/46808230-81a86f80-cd74-11e8-805e-972641eebac7.png">

**Homepage buttons**
<img width="998" alt="screen shot 2018-10-11 at 16 41 04" src="https://user-images.githubusercontent.com/877919/46808231-82410600-cd74-11e8-880c-cd3a3fee05d4.png">

## Tasks

- [ ] ?

**Comment by kilemensi** [comment]
Already implemented
