### ISSUE TITLE
Improve how sensors work hardware component

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#124]
## Description
Match `how sensors work` page to the design implementation

#### Design
![image](https://user-images.githubusercontent.com/3693563/47090875-72ba3500-d22c-11e8-9307-5cbb7caed798.png)

#### Current Implementation
![image](https://user-images.githubusercontent.com/3693563/47090847-5fa76500-d22c-11e8-9345-78e412395fb2.png)

## Tasks
- [ ] Change background color to white
- [ ] Improve typography layout + font size to match the design

**Comment by kilemensi** [comment]
Already fixed.
