### ISSUE TITLE
Add  new sources component for the airborne disease page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#25]
## Description

Create a component for the *sources of air pollution* section for the airborne disease page

## Screenshots

![image](https://user-images.githubusercontent.com/3693563/44848808-cf539780-ac60-11e8-8908-353d91d673a0.png)

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] ???
- [ ] ???
- [ ] ???

**Comment by kilemensi** [comment]
Already implemented
