### ISSUE TITLE
Add air city page in the pages  directory

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#27]
## Description
Create a parent component for the air cities page to include all other child components

## Screenshots
![image](https://user-images.githubusercontent.com/3693563/44849253-332a9000-ac62-11e8-803a-04d4be82798f.png)

## Tasks
- [ ] ???
- [ ] ???
- [ ] ???

**Comment by kilemensi** [comment]
Is this still an issue @nerdlet?

**Comment by kilemensi** [comment]
I think this is already implemented at https://alpha.sensors.africa/air/city
