### ISSUE TITLE
Create graph component for the air city page

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#34]
## Description
Create a new component for the graph section of the city page

## Screenshots
![image](https://user-images.githubusercontent.com/3693563/44850412-cdd89e00-ac65-11e8-8f1c-24cf958e3707.png)

## Tasks
- [ ] ???
- [ ] ???
- [ ] ???

**Comment by kilemensi** [comment]
In PT
