### ISSUE TITLE
Improve the support component section design

### ISSUE THREAD

**Issue by nerdlet** [CodeForAfricaLabs/sensors.AFRICA#92]
## Description
Improve the support section design

## Screenshots
Current design
![image](https://user-images.githubusercontent.com/3693563/46802968-992d2b80-cd67-11e8-8be3-54f10400a9b4.png)

Expected Look

![image](https://user-images.githubusercontent.com/3693563/46805100-f9729c00-cd6c-11e8-9bef-9fda06371a83.png)

## Tasks
- [x] Add top bottom padding
- [x] Add font weight to card and button typography

**Comment by DavidLemayian** [comment]
@nerdlet Please include screenshots of designs for reference.
